//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Budget.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista transakcji;;;;;ING Bank Śląski S.A. ul. Sokolska 34, 40-086 Katowice www.ingbank.pl;;;;;;;;;;;;;;;
        ///Data wygenerowania dokumentu: 09.09.2016, 16:01;;;;;;;;;;;;;;;;;;;;
        ///
        ///Dane Użytkownika:;
        ///SZCZUDŁO MACIEJ;
        ///MIECZYKOWA 9 M.10 30-389 KRAKÓW;
        ///
        ///Wybrane rachunki:;
        ///KONTO Direct (PLN);;25 1050 1445 1000 0022 7057 4334;
        ///KONTO Direct (PLN);;93 1050 1360 1000 0022 1015 8438;
        ///Otwarte Konto Oszczędnościowe (PLN);;27 1050 1360 1000 0022 8275 2001;
        ///Zastosowane kryteria wyboru;;;;;Podsumowanie;;
        ///Zakres dat:;09.03.2016  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2018_06_All {
            get {
                return ResourceManager.GetString("_2018_06_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data operacji;Typ;Tytuł;Kwota;Notatka;Nazwa kategorii;Nazwa kategorii;Nazwa konta
        ///17-06-2016;1;Kulki;45.30;;Gry;Rozrywka;Maciek
        ///.
        /// </summary>
        internal static string czerwiec_2016_Maciek {
            get {
                return ResourceManager.GetString("czerwiec_2016_Maciek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionDate,TransactionType,Owner,Category,SubCategory,CounterPartData,Amount,Currency,Title,Details,AccountNumber,TransactionNumber
        ///41246,WYDATEK,Jolka,,,4246xx9859 UL. KAMIENSKIEGO 11 KRAK OW ,-200,PLN,TRANSAKCJA WYPŁATY 30.11.2012 BANKOMAT OBCY ,TR.KART -200.00 ,,2,01233897302598E+17
        ///41246,WYDATEK,Jolka,,,4246xx9859 SHELL 02 Krakow ,-249,76,PLN,TRANSAKCJA ZAKUPU 30.11.2012 ,TR.KART -249.76 ,,2,01233897304372E+17
        ///41246,WYDATEK,Jolka,,,4246xx9859 ZARA Bonarka Krakow ,-135,8,PLN,TRANSAKCJA ZAKUPU 30. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transactionsToParseToCategories {
            get {
                return ResourceManager.GetString("transactionsToParseToCategories", resourceCulture);
            }
        }
    }
}
